# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gazebo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pose_pb2 as pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gazebo.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cgazebo.proto\x1a\npose.proto\"<\n\tModelSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x13\n\x04pose\x18\x03 \x01(\x0b\x32\x05.Pose\"+\n\rGazeboCommand\x12\x1a\n\x06models\x18\x01 \x03(\x0b\x32\n.ModelSpec\"+\n\rGazeboObserve\x12\x1a\n\x06models\x18\x01 \x03(\x0b\x32\n.ModelSpecb\x06proto3')
  ,
  dependencies=[pose__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODELSPEC = _descriptor.Descriptor(
  name='ModelSpec',
  full_name='ModelSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ModelSpec.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='ModelSpec.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ModelSpec.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=88,
)


_GAZEBOCOMMAND = _descriptor.Descriptor(
  name='GazeboCommand',
  full_name='GazeboCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='GazeboCommand.models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=133,
)


_GAZEBOOBSERVE = _descriptor.Descriptor(
  name='GazeboObserve',
  full_name='GazeboObserve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='GazeboObserve.models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=178,
)

_MODELSPEC.fields_by_name['pose'].message_type = pose__pb2._POSE
_GAZEBOCOMMAND.fields_by_name['models'].message_type = _MODELSPEC
_GAZEBOOBSERVE.fields_by_name['models'].message_type = _MODELSPEC
DESCRIPTOR.message_types_by_name['ModelSpec'] = _MODELSPEC
DESCRIPTOR.message_types_by_name['GazeboCommand'] = _GAZEBOCOMMAND
DESCRIPTOR.message_types_by_name['GazeboObserve'] = _GAZEBOOBSERVE

ModelSpec = _reflection.GeneratedProtocolMessageType('ModelSpec', (_message.Message,), dict(
  DESCRIPTOR = _MODELSPEC,
  __module__ = 'gazebo_pb2'
  # @@protoc_insertion_point(class_scope:ModelSpec)
  ))
_sym_db.RegisterMessage(ModelSpec)

GazeboCommand = _reflection.GeneratedProtocolMessageType('GazeboCommand', (_message.Message,), dict(
  DESCRIPTOR = _GAZEBOCOMMAND,
  __module__ = 'gazebo_pb2'
  # @@protoc_insertion_point(class_scope:GazeboCommand)
  ))
_sym_db.RegisterMessage(GazeboCommand)

GazeboObserve = _reflection.GeneratedProtocolMessageType('GazeboObserve', (_message.Message,), dict(
  DESCRIPTOR = _GAZEBOOBSERVE,
  __module__ = 'gazebo_pb2'
  # @@protoc_insertion_point(class_scope:GazeboObserve)
  ))
_sym_db.RegisterMessage(GazeboObserve)


# @@protoc_insertion_point(module_scope)
